heat_template_version: '2016-10-14'

parameters:
  index:
    type: number
  instance_type:
    type: string

conditions:
  add_vol_b: {equals : [{get_param: instance_type}, "node"]}

resources:
  node:
    type: OS::Nova::Server
    properties:
      flavor: 'm1.xlarge'
      name:
        str_replace:
          template: instance_type%-index%.openshift.vub.lt
          params:
            "index%": { get_param: index }
            "instance_type%": { get_param: instance_type }
      image: 'a598e364-20e3-4ad9-82a0-247139e2fb17'
      key_name: 'simonas'
      networks:
      - network: PrivateForVlan10
      security_groups: [default,AllowAll]
      user_data: |
        #!/bin/bash
        yum upgrade -y
  volume_a:
    type: OS::Cinder::Volume
    properties:
      size: 100
  volume_attachment_a:
    type: OS::Cinder::VolumeAttachment
    depends_on:
      - node
      - volume_a
    properties:
      volume_id: { get_resource: volume_a }
      instance_uuid: { get_resource: node }
  volume_b:
    type: OS::Cinder::Volume
    condition: add_vol_b
    properties:
      size: 200
  volume_attachment_b:
    type: OS::Cinder::VolumeAttachment
    condition: add_vol_b
    depends_on:
      - node
      - volume_b
    properties:
      volume_id: { get_resource: volume_b }
      instance_uuid: { get_resource: node }
